-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE TYPE public.order_status AS ENUM
    ('pending', 'processing', 'shipped', 'delivered', 'cancelled');



CREATE TABLE IF NOT EXISTS public.categories
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(100) COLLATE pg_catalog."default" NOT NULL,
    gender character varying(100) COLLATE pg_catalog."default" NOT NULL,
    parent_id integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT categories_pkey PRIMARY KEY (id),
    CONSTRAINT categories_slug_key UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.favorites
(
    user_id integer NOT NULL,
    product_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT favorites_pkey PRIMARY KEY (user_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.order_items
(
    id serial NOT NULL,
    order_id integer NOT NULL,
    product_variant_id integer,
    quantity integer NOT NULL,
    unit_price numeric(10, 2) NOT NULL,
    CONSTRAINT order_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id serial NOT NULL,
    user_id integer,
    total_amount numeric(10, 2) NOT NULL,
    status order_status DEFAULT 'pending'::order_status,
    shipping_address text COLLATE pg_catalog."default" NOT NULL,
    stripe_payment_id character varying(255) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_variants
(
    id serial NOT NULL,
    product_id integer NOT NULL,
    size character varying(10) COLLATE pg_catalog."default" NOT NULL,
    stock_quantity integer DEFAULT 0,
    CONSTRAINT product_variants_pkey PRIMARY KEY (id),
    CONSTRAINT product_variants_product_id_size_key UNIQUE (product_id, size)
);

CREATE TABLE IF NOT EXISTS public.products
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    price numeric(10, 2) NOT NULL,
    category_id integer,
    brand character varying(100) COLLATE pg_catalog."default",
    color character varying(50) COLLATE pg_catalog."default",
    image_url text COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT products_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(100) COLLATE pg_catalog."default",
    role character varying(20) COLLATE pg_catalog."default" DEFAULT 'client'::character varying,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.addresses
(
    id serial NOT NULL,
    user_id integer,
    name character varying(255) NOT NULL,
    street character varying(255) NOT NULL,
    city character varying(100) NOT NULL,
    zip_code character varying(20) NOT NULL,
    country character varying(100) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT addresses_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.categories
    ADD CONSTRAINT categories_parent_id_fkey FOREIGN KEY (parent_id)
    REFERENCES public.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.favorites
    ADD CONSTRAINT favorites_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.favorites
    ADD CONSTRAINT favorites_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT order_items_variant_fkey FOREIGN KEY (product_variant_id)
    REFERENCES public.product_variants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.product_variants
    ADD CONSTRAINT product_variants_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;

ALTER TABLE IF EXISTS public.addresses
    ADD CONSTRAINT addresses_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;



-- Women Categories
INSERT INTO public.categories (name, slug, gender) VALUES
('Coats & Jackets', 'women-coats-jackets', 'Women'),
('Dresses', 'women-dresses', 'Women'),
('Tops & Shirts', 'women-tops-shirts', 'Women'),
('Pants', 'women-pants', 'Women'),
('Knitwear', 'women-knitwear', 'Women'),
('Skirts', 'women-skirts', 'Women'),
('Shoes', 'women-shoes', 'Women'),
('Bags', 'women-bags', 'Women')
ON CONFLICT (slug) DO NOTHING;

-- Men Categories
INSERT INTO public.categories (name, slug, gender) VALUES
('Suits & Blazers', 'men-suits-blazers', 'Men'),
('Shirts', 'men-shirts', 'Men'),
('Trousers', 'men-trousers', 'Men'),
('Jeans', 'men-jeans', 'Men'),
('Outerwear', 'men-outerwear', 'Men'),
('Shoes', 'men-shoes', 'Men'),
('Accessories', 'men-accessories', 'Men')
ON CONFLICT (slug) DO NOTHING;

-- Accessories Categories
INSERT INTO public.categories (name, slug, gender) VALUES
('Bags', 'acc-bags', 'Accessories'),
('Jewelry', 'acc-jewelry', 'Accessories'),
('Watches', 'acc-watches', 'Accessories'),
('Sunglasses', 'acc-sunglasses', 'Accessories'),
('Hats', 'acc-hats', 'Accessories')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.users (email, password_hash, full_name, role)
VALUES ('admin@admin.com', '$2b$12$tkSPEOt2ZpVJvKjdnzd49eq8KzN31Pa5d7XVWF8BHUt9pkaKgnlu2', 'Admin User', 'admin')
ON CONFLICT (email) DO NOTHING;

INSERT INTO public.products VALUES (1, 'Padded Cassette Bag', 'A signature intrecciato woven leather shoulder bag with a padded effect. Iconic and timeless.', 550.00, 8, 'Aesop', 'Green', 'https://media-cdn.printemps.com/image/92/2/8418922.png?fit=bounds&bg-color=F8F8F8&width=571&height=782&canvas=571-782', true, '2026-01-16 09:38:49.490991+00');
INSERT INTO public.products VALUES (2, 'So Kate 120 Patent Pumps', 'The iconic pumps with a steep 120mm heel and signature red sole. A symbol of confidence and glamour.', 1150.00, 7, 'Chanel', 'Black', 'https://media-cdn.printemps.com/image/30/1/8729301.jpeg?fit=bounds&bg-color=F8F8F8&width=571&height=782&canvas=571-782', true, '2026-01-16 09:41:54.516996+00');
INSERT INTO public.products VALUES (3, 'Re-Edition 2005 Re-Nylon Bag', 'feminine reimagining of the iconic 2000s shape, made from innovative Re-Nylon. Saffiano leather details.', 950.00, 8, 'Prada', 'Blue', 'https://media-cdn.printemps.com/image/23/7/8602237.jpeg?fit=bounds&bg-color=F8F8F8&width=571&height=782&canvas=571-782', true, '2026-01-16 09:43:27.914366+00');
INSERT INTO public.products VALUES (4, 'Classic Trench Coat', 'The definitive Kensington fit trench coat in bespoke gabardine. Archive-inspired design.', 560.00, 1, 'Gucci', 'Beige', 'https://media-cdn.printemps.com/image/14/2/8609142.jpeg?fit=bounds&bg-color=F8F8F8&width=571&height=782&canvas=571-782', true, '2026-01-16 09:47:16.029062+00');
INSERT INTO public.products VALUES (5, 'Marmont MatelassÃ© Bag', 'The GG Marmont chain shoulder bag has a softly structured shape and an oversized flap closure with Double G hardware.', 2300.00, 8, 'Gucci', 'Black', 'https://media.gucci.com/style/White_South_0_160_316x316/1739468753/837267_AAE38_1000_002_066_0000_Light-Sac-paule-GGMarmont-moyen-format.jpg', true, '2026-01-16 09:53:35.787119+00');
INSERT INTO public.products VALUES (6, 'J''Adior Slingback Pumps', 'A prime example of the House''s savoir-faire, crafted in black technical fabric with the J''Adior ribbon.', 1099.00, 7, 'Dior', 'Blue', 'https://assets.christiandior.com/is/image/diorprod/KCV508OCCS32N_SBG_E02-2?$r9x10_raw$&crop=0,0,4000,5000&wid=1024&hei=1107&scale=0.5535&bfc=on&qlt=85', true, '2026-01-16 09:55:38.064495+00');
INSERT INTO public.products VALUES (7, 'Satin Effect Dress', 'Long dress with a V-neck and thin straps. Detailed with gathered seams.', 675.00, 2, 'Zara', 'Black', 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQANEoiJBRIPb4WJfGssE7zrtSc4OljXJufcIgG9fGj4VuxskDBzwV1bei_NY0WnsYsOZi4P3pQL-ViR0qDRHW0mzPulv7AvZmsoRUn4PBx_edM4RFEr_jc2F8', true, '2026-01-16 10:37:16.617745+00');
INSERT INTO public.products VALUES (8, 'Silk Bow Blouse', 'A romantic silk crepe de chine blouse with a detachable neck bow. Sophisticated and versatile.', 980.00, 3, 'Gucci', 'Brown', 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSdXeYSe-lVC3A7vVRJ0gN1OS0fdwURhSWKlbOeBq3yLbJ9IGAHtXus7Vo74E5ud2aAl4N4JL-bfa4PXo3G2tmG7vr69F6XuHVgyU_1_a-ctdh-rxfUpjjXvXZc', true, '2026-01-16 10:38:57.91072+00');
INSERT INTO public.products VALUES (9, 'B27 Low-Top Sneaker', 'A signature Dior sneaker combining smooth calfskin with Dior Oblique Galaxy leather.', 1244.00, 14, 'Dior', 'Black', 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTPFQMnW2EZ4VfDt0bnjzEtw_Wg6tyocmdtCaMzRiAEXTcuNk-Eq7w2en3Ul5k8bfkA0-IWOJBpcnZ0lYLV3_hDd2FDQoJpRPJIYutpCYLMkb4z2IQ8SZnf', true, '2026-01-16 10:41:29.750311+00');
INSERT INTO public.products VALUES (10, 'Saddle Bag	', 'The iconic Saddle bag reimagined for men in black grained calfskin with an industrial buckle.', 999.99, 15, 'Dior', 'Black', 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcStqyymceMnYZCKjQFUULh4oZW8hCNHzYa6Uc1u9VZo_JRL5XYx4Nu5GwCqlLAmAX9DaAaaZ8buFVz9S_lFCfuVaUSLDZqgBotnzbFvZEXVEkOg-1hz2gGQRleN', true, '2026-01-16 10:42:30.800262+00');
INSERT INTO public.products VALUES (12, 'Re-Nylon Shirt	', 'A boxy fit shirt made from Re-Nylon, contrasting sustainability with luxury utility.', 1700.00, 10, 'Prada', 'Brown', 'https://www.prada.com/content/dam/pradabkg_products/S/SC8/SC823M/1WQ9F0324/SC823M_1WQ9_F0324_S_OOO_SLF.jpg/_jcr_content/renditions/cq5dam.web.hebebed.2000.2000.jpg', true, '2026-01-16 10:45:10.652387+00');
INSERT INTO public.products VALUES (11, 'GG Cotton Jacket', 'A cotton canvas jacket featuring the distinctive GG embroidery throughout.', 1900.00, 13, 'Gucci', 'Red', 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcS6BTfVWsaIdUoLeeGXno32csYL1YVG2rgrAF0ket8nq5bhc8y-yNBb_X-wN6LWtPbE-HF96sAwgwxHAZ4Md21X155xfqrteg', true, '2026-01-16 10:44:06.704577+00');
INSERT INTO public.products VALUES (13, 'Oversized Puffer Jacket', 'High-collar puffer jacket with long sleeves and elastic cuffs. Streetwear aesthetic.', 640.00, 13, 'Zara', 'Grey', 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcToNYDHdlxWJpsKBAHjqZfhZG54ZEXgepuICUe7KpR3BHOMQH9dhqacw3AxT8Z3CiLIRQ90IjM1PpyfgODBuuXYgYSDUilvKW_w_gPAiEo', true, '2026-01-16 10:48:19.792273+00');
INSERT INTO public.products VALUES (14, 'Ace Embroidered Sneaker', 'The retro-inspired leather sneaker featuring the house''s signature green and red Web strip.', 1242.00, 7, 'Gucci', 'Multi', 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTPAgFB2lfBlQj3DnFlm9jq5yc0E6JawH0gJ-OBmqOiyHABtE9tb5iNdzj413WtJR1Bi4CfltBYvRxBdGsQrb30aJ90ARsJi-7j_Fgmw9Fy-y5HZuE-lKRoj8E', true, '2026-01-16 11:16:44.538527+00');
INSERT INTO public.products VALUES (15, 'Wool Crewneck Sweater', 'Slim fit suit crafted from slightly stretch fabric for added comfort. Features a jacket with notched lapels and two-button fastening, paired with matching flat-front trousers. A versatile essential for both office wear and special occasions', 0.00, 9, 'La Mer', 'Blue', 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcT3M3BkSuZKVF4mBZSQv6RE0w-nvqamOTnlgW23PVw64Bk-5Bh8jXlsAD7KQl97INSQZ54hpluAEI2696AnnB16gB04PyO_KW0TwN0O1PWEevCyJXd7mRD6', true, '2026-01-16 11:19:28.290658+00');

END;INSERT INTO public.product_variants VALUES (1, 1, 'XS', 100);
INSERT INTO public.product_variants VALUES (2, 1, 'S', 100);
INSERT INTO public.product_variants VALUES (3, 1, 'M', 100);
INSERT INTO public.product_variants VALUES (4, 1, 'L', 100);
INSERT INTO public.product_variants VALUES (5, 1, 'XL', 100);
INSERT INTO public.product_variants VALUES (6, 2, 'XS', 100);
INSERT INTO public.product_variants VALUES (7, 2, 'S', 100);
INSERT INTO public.product_variants VALUES (8, 2, 'M', 100);
INSERT INTO public.product_variants VALUES (9, 2, 'L', 100);
INSERT INTO public.product_variants VALUES (10, 2, 'XL', 100);
INSERT INTO public.product_variants VALUES (11, 3, 'XS', 100);
INSERT INTO public.product_variants VALUES (12, 3, 'S', 100);
INSERT INTO public.product_variants VALUES (13, 3, 'M', 100);
INSERT INTO public.product_variants VALUES (14, 3, 'L', 100);
INSERT INTO public.product_variants VALUES (15, 3, 'XL', 100);
INSERT INTO public.product_variants VALUES (16, 4, 'XS', 100);
INSERT INTO public.product_variants VALUES (17, 4, 'S', 100);
INSERT INTO public.product_variants VALUES (18, 4, 'M', 100);
INSERT INTO public.product_variants VALUES (19, 4, 'L', 100);
INSERT INTO public.product_variants VALUES (20, 4, 'XL', 100);
INSERT INTO public.product_variants VALUES (21, 5, 'XS', 100);
INSERT INTO public.product_variants VALUES (22, 5, 'S', 100);
INSERT INTO public.product_variants VALUES (23, 5, 'M', 100);
INSERT INTO public.product_variants VALUES (24, 5, 'L', 100);
INSERT INTO public.product_variants VALUES (25, 5, 'XL', 100);
INSERT INTO public.product_variants VALUES (26, 6, 'XS', 100);
INSERT INTO public.product_variants VALUES (27, 6, 'S', 100);
INSERT INTO public.product_variants VALUES (28, 6, 'M', 100);
INSERT INTO public.product_variants VALUES (29, 6, 'L', 100);
INSERT INTO public.product_variants VALUES (30, 6, 'XL', 100);
INSERT INTO public.product_variants VALUES (31, 7, 'XS', 100);
INSERT INTO public.product_variants VALUES (32, 7, 'S', 100);
INSERT INTO public.product_variants VALUES (33, 7, 'M', 100);
INSERT INTO public.product_variants VALUES (34, 7, 'L', 100);
INSERT INTO public.product_variants VALUES (35, 7, 'XL', 100);
INSERT INTO public.product_variants VALUES (36, 8, 'XS', 100);
INSERT INTO public.product_variants VALUES (37, 8, 'S', 100);
INSERT INTO public.product_variants VALUES (38, 8, 'M', 100);
INSERT INTO public.product_variants VALUES (39, 8, 'L', 100);
INSERT INTO public.product_variants VALUES (40, 8, 'XL', 100);
INSERT INTO public.product_variants VALUES (41, 9, 'XS', 100);
INSERT INTO public.product_variants VALUES (42, 9, 'S', 100);
INSERT INTO public.product_variants VALUES (43, 9, 'M', 100);
INSERT INTO public.product_variants VALUES (44, 9, 'L', 100);
INSERT INTO public.product_variants VALUES (45, 9, 'XL', 100);
INSERT INTO public.product_variants VALUES (46, 10, 'XS', 100);
INSERT INTO public.product_variants VALUES (47, 10, 'S', 100);
INSERT INTO public.product_variants VALUES (48, 10, 'M', 100);
INSERT INTO public.product_variants VALUES (49, 10, 'L', 100);
INSERT INTO public.product_variants VALUES (50, 10, 'XL', 100);
INSERT INTO public.product_variants VALUES (51, 11, 'XS', 100);
INSERT INTO public.product_variants VALUES (52, 11, 'S', 100);
INSERT INTO public.product_variants VALUES (53, 11, 'M', 100);
INSERT INTO public.product_variants VALUES (54, 11, 'L', 100);
INSERT INTO public.product_variants VALUES (55, 11, 'XL', 100);
INSERT INTO public.product_variants VALUES (56, 12, 'XS', 100);
INSERT INTO public.product_variants VALUES (57, 12, 'S', 100);
INSERT INTO public.product_variants VALUES (58, 12, 'M', 100);
INSERT INTO public.product_variants VALUES (59, 12, 'L', 100);
INSERT INTO public.product_variants VALUES (60, 12, 'XL', 100);
INSERT INTO public.product_variants VALUES (61, 13, 'XS', 100);
INSERT INTO public.product_variants VALUES (62, 13, 'S', 100);
INSERT INTO public.product_variants VALUES (63, 13, 'M', 100);
INSERT INTO public.product_variants VALUES (64, 13, 'L', 100);
INSERT INTO public.product_variants VALUES (65, 13, 'XL', 100);
INSERT INTO public.product_variants VALUES (66, 14, 'XS', 100);
INSERT INTO public.product_variants VALUES (67, 14, 'S', 100);
INSERT INTO public.product_variants VALUES (68, 14, 'M', 100);
INSERT INTO public.product_variants VALUES (69, 14, 'L', 100);
INSERT INTO public.product_variants VALUES (70, 14, 'XL', 100);
INSERT INTO public.product_variants VALUES (71, 15, 'XS', 100);
INSERT INTO public.product_variants VALUES (72, 15, 'S', 100);
INSERT INTO public.product_variants VALUES (73, 15, 'M', 100);
INSERT INTO public.product_variants VALUES (74, 15, 'L', 100);
INSERT INTO public.product_variants VALUES (75, 15, 'XL', 100);