-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE TYPE public.order_status AS ENUM
    ('pending', 'processing', 'shipped', 'delivered', 'cancelled');



CREATE TABLE IF NOT EXISTS public.categories
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(100) COLLATE pg_catalog."default" NOT NULL,
    gender character varying(100) COLLATE pg_catalog."default" NOT NULL,
    parent_id integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT categories_pkey PRIMARY KEY (id),
    CONSTRAINT categories_slug_key UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.favorites
(
    user_id integer NOT NULL,
    product_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT favorites_pkey PRIMARY KEY (user_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.order_items
(
    id serial NOT NULL,
    order_id integer NOT NULL,
    product_variant_id integer,
    quantity integer NOT NULL,
    unit_price numeric(10, 2) NOT NULL,
    CONSTRAINT order_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id serial NOT NULL,
    user_id integer,
    total_amount numeric(10, 2) NOT NULL,
    status order_status DEFAULT 'pending'::order_status,
    shipping_address text COLLATE pg_catalog."default" NOT NULL,
    stripe_payment_id character varying(255) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_variants
(
    id serial NOT NULL,
    product_id integer NOT NULL,
    size character varying(10) COLLATE pg_catalog."default" NOT NULL,
    stock_quantity integer DEFAULT 0,
    CONSTRAINT product_variants_pkey PRIMARY KEY (id),
    CONSTRAINT product_variants_product_id_size_key UNIQUE (product_id, size)
);

CREATE TABLE IF NOT EXISTS public.products
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    price numeric(10, 2) NOT NULL,
    category_id integer,
    brand character varying(100) COLLATE pg_catalog."default",
    color character varying(50) COLLATE pg_catalog."default",
    image_url text COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT products_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(100) COLLATE pg_catalog."default",
    role character varying(20) COLLATE pg_catalog."default" DEFAULT 'client'::character varying,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.addresses
(
    id serial NOT NULL,
    user_id integer,
    name character varying(255) NOT NULL,
    street character varying(255) NOT NULL,
    city character varying(100) NOT NULL,
    zip_code character varying(20) NOT NULL,
    country character varying(100) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT addresses_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.categories
    ADD CONSTRAINT categories_parent_id_fkey FOREIGN KEY (parent_id)
    REFERENCES public.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.favorites
    ADD CONSTRAINT favorites_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.favorites
    ADD CONSTRAINT favorites_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT order_items_variant_fkey FOREIGN KEY (product_variant_id)
    REFERENCES public.product_variants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.product_variants
    ADD CONSTRAINT product_variants_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;

ALTER TABLE IF EXISTS public.addresses
    ADD CONSTRAINT addresses_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;



-- Women Categories
INSERT INTO public.categories (name, slug, gender) VALUES
('Coats & Jackets', 'women-coats-jackets', 'Women'),
('Dresses', 'women-dresses', 'Women'),
('Tops & Shirts', 'women-tops-shirts', 'Women'),
('Pants', 'women-pants', 'Women'),
('Knitwear', 'women-knitwear', 'Women'),
('Skirts', 'women-skirts', 'Women'),
('Shoes', 'women-shoes', 'Women'),
('Bags', 'women-bags', 'Women')
ON CONFLICT (slug) DO NOTHING;

-- Men Categories
INSERT INTO public.categories (name, slug, gender) VALUES
('Suits & Blazers', 'men-suits-blazers', 'Men'),
('Shirts', 'men-shirts', 'Men'),
('Trousers', 'men-trousers', 'Men'),
('Jeans', 'men-jeans', 'Men'),
('Outerwear', 'men-outerwear', 'Men'),
('Shoes', 'men-shoes', 'Men'),
('Accessories', 'men-accessories', 'Men')
ON CONFLICT (slug) DO NOTHING;

-- Accessories Categories
INSERT INTO public.categories (name, slug, gender) VALUES
('Bags', 'acc-bags', 'Accessories'),
('Jewelry', 'acc-jewelry', 'Accessories'),
('Watches', 'acc-watches', 'Accessories'),
('Sunglasses', 'acc-sunglasses', 'Accessories'),
('Hats', 'acc-hats', 'Accessories')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.users (email, password_hash, full_name, role)
VALUES ('admin@admin.com', '$2b$12$tkSPEOt2ZpVJvKjdnzd49eq8KzN31Pa5d7XVWF8BHUt9pkaKgnlu2', 'Admin User', 'admin')
ON CONFLICT (email) DO NOTHING;

END;